const BLACK_LIST = [
  'doc',
  'docs',
  'document',
  'documents',
  'form',
  'forms',
  'sheet',
  'sheets',
  'spreadsheet',
  'spreadsheets',
  'site',
  'sites',
  'website',
  'slide',
  'slides',
  'deck',
  'presentation',
]

const TYPES_MAP = {
  "blog": "https://medium.com/new-story",
  "drawing": "https://docs.google.com/drawings/create",
  "email": "https://mail.google.com/mail/u/0/#inbox?compose=new",
  "gif": "https://giphy.com/upload",
  "gist": "https://gist.github.com/",
  "image": "https://imgur.com/upload",
  "issue": null,
  "pen": "https://codepen.io/pen",
  "pin": "https://www.pinterest.com/pin-builder",
  "post": "https://www.reddit.com/submit",
  "product": "https://www.producthunt.com/posts/new",
  "project": "https://www.behance.net/portfolio/editor",
  "repo": "https://github.com/new",
  "sandbox": "https://codesandbox.io/s/",
  "shot": "https://dribbble.com/shots/new",
  "subreddit": "https://www.reddit.com/subreddits/create",
  "thread": "https://spectrum.chat/new/thread",
  "tweet": "https://twitter.com/compose/tweet",
}
